<<<<<<< HEAD
# Generated by Django 6.1 on 2026-09-30 04:04
=======
# Generated by Django 6.1 on 2026-09-09 00:38
>>>>>>> 4258492eabc3b27888c830d3b57420bf9f0d97cf

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=70)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='catalogo.proveedor'),
            preserve_default=False,
        ),
    ]
